import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950 text-white">
        <div className="flex-grow">{children}</div>
        <footer className="w-full bg-zinc-950 border-t border-zinc-900 py-8 px-4 text-center mt-auto">
          <p className="text-zinc-500 text-xs md:text-sm max-w-4xl mx-auto leading-relaxed">
            <strong className="font-semibold text-zinc-400">Strict Legal Disclaimer:</strong> LienResolve provides technical document-formatting based on the 2026 SOP. We are not a law firm and this does not constitute legal advice.
          </p>
        </footer>
      </body>
    </html>
  );
}
